# i have 2 files 01_dataprep.py and 02_datapreproces.py
name: HGV Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: iterative/setup-cml@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: data prep
      run: |
        python 01_dataprep.py --cities_pool NewYork LosAngeles Chicago Houston Phoenix Philadelphia SanAntonio --dirty_records_prob 0.5 --num_files 5000 --num_records_range 50 100
    - name: data preprocess
      run: |
        python 02_dataPreprocess.py
    - name: Evaluate
      env :
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          echo "## Model Metrics" >> report.md
          cat preprocess.log >> report.md
  
          # echo "## confusoion matrix" >> report.md
          # echo "![confusion matrix](result.png)" >> report.md
  
          cml comment create report.md
